### ISSUE TITLE
性能对比

### ISSUE THREAD

**Issue by ericxsun** [XiaoMi/MiNLP#11]
对贵司的开源，为中文NLP做出了一些贡献，表示非常感谢、点赞。但这套新开源组件有什么优点/特点还缺少文档让读者能快速和更好地理解及使用。同时目前市面上不少公司/学术机构都开源了各自的分词套件（分词、词性、实体、句法等），比如

- 百度 LAC：https://github.com/baidu/lac
- 清华 LAC：https://github.com/thunlp/THULAC
- 哈工大 LAC：https://github.com/HIT-SCIR/ltp

等等

能否出一个「性能对比」呢：

- 分词效果，Precision, Recall 等
- 分词速度

等等

**Comment by nepshi** [comment]
您好，感谢您的支持。我们的分词工具以PKU分词标准为依据，README中记录了我们分词工具在SIGHAN 2005 PKU测试集上的分词效果：粗、细粒度的F1分别是95.7%和96.3%，分词速度在一台主流PC上大约是50KB/s，目前我们正在对模型优化，进一步提升速度。
您提到的多个LAC等工具，我们内部都有详细的对比评测，之所以没有放出，是考虑到测试环境的差异，对比结果难以保证公平，很多工具都会在主页上给出标准测试集上的结果，您可以横向对比查看，如果没有给出，我们建议可以自行评测，方法也比较简单，SIGHAN 2005提供了相应的测试数据和脚本：http://sighan.cs.uchicago.edu/bakeoff2005/

**Comment by ericxsun** [comment]
非常感谢
