### ISSUE TITLE
[DUCK]x小时x分(后)?，抽取错误（分钟表达是latent类型）

### ISSUE THREAD

**Issue by zhangsonglei** [XiaoMi/MiNLP#111]
示例query：
1小时05分  
1小时05分后  
1小时5分  
1小时5分后  
一小时五分  
一小时五分后  
一小时零五分  
一小时零五分后

**Comment by du00cs** [comment]
- `1小时05分`: 这应该是duration ? 正确
- time + `1小时05分后`: 正确
- `一年前的今天`: 正确

确认错误
1. 一小时零五分，未成功组合
2. 一小时五分，五分是一个latent表达，被滤掉了，需要放出来
