### ISSUE TITLE
tf2.0.0不支持对吗

### ISSUE THREAD

**Issue by gaowenxin95** [XiaoMi/MiNLP#12]
请问一下，我看版本是tf<2,想double check下，tf2.0.0不支持对吗？
@lshmouse @llhe @54chen

**Comment by nepshi** [comment]
支持，但是需要手动操作。安装MiNLP-Tokenizer之后，手动更新tf到2.0以上版本。
最近我们正在进行完整的兼容性测试，包括python的版本和tf的版本，这两天会放出一个新的版本，去掉对tf<2的要求。

**Comment by nepshi** [comment]
已更新，支持：Python 3.5~3.8，TensorFlow>=1.14

**Comment by jackiegeek** [comment]
我看pypi上的还没有更新，pip install minlp-tokenizer 之后有报错
```
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu<2,>=1.15 (from minlp-tokenizer) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3)
ERROR: No matching distribution found for tensorflow-gpu<2,>=1.15 (from minlp-tokenizer)
```

**Comment by guoyuankai** [comment]
> 我看pypi上的还没有更新，pip install minlp-tokenizer 之后有报错
> 
> ```
> ERROR: Could not find a version that satisfies the requirement tensorflow-gpu<2,>=1.15 (from minlp-tokenizer) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3)
> ERROR: No matching distribution found for tensorflow-gpu<2,>=1.15 (from minlp-tokenizer)
> ```
pip源上应该2020.11.27日完成更新3.2.3版本的更新，TensorFlow2系列版本也已经支持。请检查一下您的pip版本，更新pip，或者pip install minlp-tokenizer==3.2.3 进行尝试。

**Comment by jackiegeek** [comment]
似乎是跟我的conda环境有关系，切换了conda环境，就下载成功了，否则只能强行指定来源：
`pip install https://mirrors.aliyun.com/pypi/packages/8e/60/b975d9b5b9f7c5416e58cbff16894de259733b78031875226600438b16ad/minlp-tokenizer-3.2.3.tar.gz `

**Comment by guoyuankai** [comment]
> 似乎是跟我的conda环境有关系，切换了conda环境，就下载成功了，否则只能强行指定来源：
> `pip install https://mirrors.aliyun.com/pypi/packages/8e/60/b975d9b5b9f7c5416e58cbff16894de259733b78031875226600438b16ad/minlp-tokenizer-3.2.3.tar.gz `

感谢您的反馈，我们后续会添加相关说明。
