### ISSUE TITLE
关于在GPU分词下的多线程优化的建议

### ISSUE THREAD

**Issue by aseaday** [XiaoMi/MiNLP#19]
Hi，感谢你们的工作，目前还是很喜欢MI Tokenizer，对比其他分词。粗粒度分词在翻译和训练生成模型下很有帮助，考虑到后续的 subword 处理。
目前，在使用时，遇到几个问题, 我整理了一些解决方案, 希望和你们一起讨论。
1. GPU下，batch 我看配置512，但是GPU显存没有设限制，以至于单进程跑很吃亏，所以我在我的实际使用中，做了优化，允许多线程共享显存来提高效率，使得GPU利用率能到10%-15%。
2. 我进一步探求了为什么还是比较低，评估下来，有一些CPU的计算代码的消耗还是严重的，比如在cut batch的tag2words消耗的时间几乎和一样久。我觉得这个地方可能需要更好的数据拷贝机制，避免堵塞。

我会先提一个PR看看提供一个多进程的GPU切词方法，有时间的话，想一起讨论第二个问题，一个是一些CPU代码的优化，比如vterbi过程也可以迁移到cuda上。希望听一下你们的反馈。

我的初衷是希望有一个非常快速的基于预训练模型的分词算法，进一步支撑行业的大规模使用。

**Comment by guoyuankai** [comment]
> Hi，感谢你们的工作，目前还是很喜欢MI Tokenizer，对比其他分词。粗粒度分词在翻译和训练生成模型下很有帮助，考虑到后续的 subword 处理。
> 目前，在使用时，遇到几个问题, 我整理了一些解决方案, 希望和你们一起讨论。
> 
> 1. GPU下，batch 我看配置512，但是GPU显存没有设限制，以至于单进程跑很吃亏，所以我在我的实际使用中，做了优化，允许多线程共享显存来提高效率，使得GPU利用率能到10%-15%。
> 2. 我进一步探求了为什么还是比较低，评估下来，有一些CPU的计算代码的消耗还是严重的，比如在cut batch的tag2words消耗的时间几乎和一样久。我觉得这个地方可能需要更好的数据拷贝机制，避免堵塞。
> 
> 我会先提一个PR看看提供一个多进程的GPU切词方法，有时间的话，想一起讨论第二个问题，一个是一些CPU代码的优化，比如vterbi过程也可以迁移到cuda上。希望听一下你们的反馈。
> 
> 我的初衷是希望有一个非常快速的基于预训练模型的分词算法，进一步支撑行业的大规模使用。

非常感谢您的贡献，我们也希望能够对效率上进行优化，十分希望能就效率问题进一步的讨论

**Comment by aseaday** [comment]
我已经提供了一个 Patch。我周末会看一下Vertbi在cuda的部分。
