### ISSUE TITLE
用多少语料训练的呢？

### ISSUE THREAD

**Issue by SunShuoying** [XiaoMi/MiNLP#21]
你好，能问一下用了多少语料训练的模型吗？

**Comment by guoyuankai** [comment]
> 你好，能问一下用了多少语料训练的模型吗？

目前使用的训练语料为收集到约1.1G的语料数据，以微博，新闻为主要来源。

**Comment by SunShuoying** [comment]
哦哦，是人工标注的吗？还是用自动化的方式进行标注的呢？

**Comment by guoyuankai** [comment]
> 哦哦，是人工标注的吗？还是用自动化的方式进行标注的呢？

我们使用了自动化标注的方式，对标注结果进行一些人工的规则修正，以尽可能的符合我们的标注规范。因此，自动化标注数据中也可能会有一些错误，人工修正时也没能发现。希望大家发现时可以提出，我们不断修正训练语料。

**Comment by SunShuoying** [comment]
> > 哦哦，是人工标注的吗？还是用自动化的方式进行标注的呢？
> 
> 我们使用了自动化标注的方式，对标注结果进行一些人工的规则修正，以尽可能的符合我们的标注规范。因此，自动化标注数据中也可能会有一些错误，人工修正时也没能发现。希望大家发现时可以提出，我们不断修正训练语料。

好的，多谢您的耐心回答。
有计划将语料开源吗？

**Comment by guoyuankai** [comment]
> > > 哦哦，是人工标注的吗？还是用自动化的方式进行标注的呢？
> > 
> > 
> > 我们使用了自动化标注的方式，对标注结果进行一些人工的规则修正，以尽可能的符合我们的标注规范。因此，自动化标注数据中也可能会有一些错误，人工修正时也没能发现。希望大家发现时可以提出，我们不断修正训练语料。
> 
> 好的，多谢您的耐心回答。
> 有计划将语料开源吗？

语料开源设计到许多因素，我们计划优先开源模型与代码，语料暂时还没有排上计划，还请谅解。后续如果有相关计划，我们也会在主页进行更新。

**Comment by SunShuoying** [comment]
@guoyuankai 嗯嗯，好的，非常期待。特别感谢你们的开源，给我提供了很大的帮助。

**Comment by guoyuankai** [comment]
> @guoyuankai 嗯嗯，好的，非常期待。特别感谢你们的开源，给我提供了很大的帮助。

谢谢大力支持，也希望能多多推荐MiNLP相关项目。定个小目标--1Kstar
