### ISSUE TITLE
[DUCK] Resource [naive_bayes.kryo] not found

### ISSUE THREAD

**Issue by WencWu** [XiaoMi/MiNLP#221]
按照以下命令启动 web 服务
```
sbt
> project server
> runMain com.xiaomi.duckling.server.DucklingApplication
```

输入 "今天天气怎么样"，报错 Resource [naive_bayes.kryo] not found

请问这个 naive_bayes.kryo 文件去哪里找？没在项目里看到

**Comment by du00cs** [comment]
`naive_bayes.kryo` 需要跑一次训练，执行一下
```bash
sbt duckModel
```
就会生成
