### ISSUE TITLE
pip install 安装失败 

### ISSUE THREAD

**Issue by Viserion-nlper** [XiaoMi/MiNLP#3]
```
 Building wheel for pyahocorasick (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Administrator\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-qgbs78j6\\pyahocorasick\\setup.py'"'"'; __file__='"'"'C:\\U
sers\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-qgbs78j6\\pyahocorasick\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__,
'"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-wheel-jvlclkkv' --python-tag cp37
       cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-qgbs78j6\pyahocorasick\
```

请问是什么原因？

目前开放的只是分词tokenizer吗？后续的词性+NER现已开放吗

**Comment by guoyuankai** [comment]
能否提供一下更加详细的安装环境说明？

**Comment by guoyuankai** [comment]
> ```
>  Building wheel for pyahocorasick (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: 'C:\Users\Administrator\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-qgbs78j6\\pyahocorasick\\setup.py'"'"'; __file__='"'"'C:\\U
> sers\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-qgbs78j6\\pyahocorasick\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__,
> '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-wheel-jvlclkkv' --python-tag cp37
>        cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-qgbs78j6\pyahocorasick\
> ```
> 
> 请问是什么原因？
> 
> 目前开放的只是分词tokenizer吗？后续的词性+NER现已开放吗

能否提供一下更加详细的安装环境说明？后续NER和词性标注将会进行开源。

**Comment by cuizhiqiang888** [comment]
![image](https://user-images.githubusercontent.com/48983651/99483354-f9581800-2998-11eb-8ecb-f8baebdcd91f.png)

**Comment by cuizhiqiang888** [comment]
跨包调用 也提示找不到 
![image](https://user-images.githubusercontent.com/48983651/99483396-11c83280-2999-11eb-9862-4761b7df3745.png)f
发现是这个问题，能否提供一些解决方案？

**Comment by guoyuankai** [comment]
> 跨包调用 也提示找不到
> ![image](https://user-images.githubusercontent.com/48983651/99483396-11c83280-2999-11eb-9862-4761b7df3745.png)f
> 发现是这个问题，能否提供一些解决方案？

请尝试更新pip和setuptools后再次从pip进行安装。还有，由于后续会开源更多项目，因此工程目录根目录为MiNLP/minlp-tokenizer 还请注意。

**Comment by Windy-Ground** [comment]
下载下来，然后用setup.py安装就好了。。。
git clone https://github.com/XiaoMi/MiNLP.git
cd MiNLP/minlp-tokenizer
pip install -r requirements.txt
python setup.py install
