### ISSUE TITLE
分词结果会把中文标点符号变成英文

### ISSUE THREAD

**Issue by stefensa** [XiaoMi/MiNLP#33]
请问有没有什么方式可以避免这种情况

**Comment by guoyuankai** [comment]
十分感谢，造成中文符号变成英文的情况是由于在预处理中全半角转换造成的bug，将尽快修复

**Comment by guoyuankai** [comment]
> 请问有没有什么方式可以避免这种情况

已经发布3.3.1版本分词工具，修复了上述bug
