### ISSUE TITLE
给一个安装环境的说明

### ISSUE THREAD

**Issue by shizhh** [XiaoMi/MiNLP#4]
是否只支持python3，tensorflow是哪个版本，等等。
目前发现在安装的时候，python2在open()报错，换到python3，在tensorflow版本报错，但看了提示信息，如下
`ERROR: Could not find a version that satisfies the requirement tensorflow<2,>=1.15 (from minlp-tokenizer) (from versions: 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0, 2.4.0rc1)
ERROR: No matching distribution found for tensorflow<2,>=1.15 (from minlp-tokenizer)`

` import tensorflow as tf;
print(tf.\_\_version\_\_);`

tf  版本 2.3.0

请问这个是什么原因

**Comment by guoyuankai** [comment]
使用的tensorflow为1.15系列版本，因此python版本应介于3.5~3.7。上述问题应该是python3.8下没有tf1对应的版本造成。后续会在readme中添加更加详细的说明。

**Comment by guoyuankai** [comment]
> 是否只支持python3，tensorflow是哪个版本，等等。
> 目前发现在安装的时候，python2在open()报错，换到python3，在tensorflow版本报错，但看了提示信息，如下
> `ERROR: Could not find a version that satisfies the requirement tensorflow<2,>=1.15 (from minlp-tokenizer) (from versions: 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0, 2.4.0rc1) ERROR: No matching distribution found for tensorflow<2,>=1.15 (from minlp-tokenizer)`
> 
> ` import tensorflow as tf; print(tf.\_\_version\_\_);`
> 
> tf 版本 2.3.0
> 
> 请问这个是什么原因

使用的tensorflow为1.15系列版本，因此python版本应介于3.5~3.7。上述问题应该是python3.8下没有tf1对应的版本造成。后续会在readme中添加更加详细的说明。

**Comment by diguacheng** [comment]
py 3.7.5
tf 1.5.0
win10 conda虚拟环境
可以稳定运行

**Comment by shizhh** [comment]
下边环境可以
python 3.7.6 
tf 1.5.4
