### ISSUE TITLE
能支持更多的日期抽取格式吗

### ISSUE THREAD

**Issue by gaewah** [XiaoMi/MiNLP#43]
![image](https://user-images.githubusercontent.com/3263175/114393746-f6222a80-9bcc-11eb-9476-d5c3de2768bf.png)
目前抽的不完整

**Comment by du00cs** [comment]
可以的！目前的主要还是面向口语表达的，带符号的基本上没怎么做，这个功能可以加上。感谢反馈。

**Comment by du00cs** [comment]
已解决 @gaewah 还请验证
