### ISSUE TITLE
分词时，怎么提高文章的字数。

### ISSUE THREAD

**Issue by pebbleren** [XiaoMi/MiNLP#66]
现在只能一次性分词500多汉字的文章。想提高到2000字，怎么增加啊。

**Comment by guoyuankai** [comment]
> 现在只能一次性分词500多汉字的文章。想提高到2000字，怎么增加啊。

理论上长度是不受限制的，如果因为OOM的问题的话，建议减小批量分词的BatchSize。如果单句也会出现OOM的问题，那么可以采用将文章按照标点先分句，再进行分词。

**Comment by pebbleren** [comment]
> > 现在只能一次性分词500多汉字的文章。想提高到2000字，怎么增加啊。
> 
> 理论上长度是不受限制的，如果因为OOM的问题的话，建议减小批量分词的BatchSize。如果单句也会出现OOM的问题，那么可以采用将文章按照标点先分句，再进行分词。

**Comment by pebbleren** [comment]
> > > 现在只能一次性分词500多汉字的文章。想提高到2000字，怎么增加啊。
> > 
> > 
> > 理论上长度是不受限制的，如果因为OOM的问题的话，建议减小批量分词的BatchSize。如果单句也会出现OOM的问题，那么可以采用将文章按照标点先分句，再进行分词。

已经解决，多谢及时回复啊，太好用了！
