### ISSUE TITLE
能将训练的代码开源吗？

### ISSUE THREAD

**Issue by cdj0311** [XiaoMi/MiNLP#7]
如题

**Comment by guoyuankai** [comment]
训练代码开源也在计划之中，因为各种原因可能还需要一段时间才能

> 如题

训练代码的开源也在计划之中，因为各种原因可能还需要一段时间，还请谅解

**Comment by guoyuankai** [comment]
> 如题

训练代码的开源在计划之中，但可能还需要一段时间，敬请期待。
